spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-5k0j8utk.bj.tencentcdb.com:10176/hibernateTest?serverTimezone=UTC
    username: root
    password: root@ruowei
  jpa:
    hibernate:
      ddl-auto: update  #      保留原来值
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  PhysicalNamingStrategyStandardImpl
    show-sql: true

    database-platform=org:
      hibernate:
        dialect:
          MySQLDialect:

